// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4m2hv4GN0__-jT-uWCkBPNeCP4yc251g',
    appId: '1:957482988455:web:abebad57fcaeb6e04cfc82',
    messagingSenderId: '957482988455',
    projectId: 'autilearn-21431',
    authDomain: 'autilearn-21431.firebaseapp.com',
    storageBucket: 'autilearn-21431.firebasestorage.app',
    measurementId: 'G-ZJX8KKMLHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByk5b5R9piGYw8c-29ixR9ygSUcWtr3h8',
    appId: '1:957482988455:android:678875427952f4f04cfc82',
    messagingSenderId: '957482988455',
    projectId: 'autilearn-21431',
    storageBucket: 'autilearn-21431.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmMaYNH72bXlR4hlFsh7QKViyp8uIR5wA',
    appId: '1:957482988455:ios:9d63dd16af1f85484cfc82',
    messagingSenderId: '957482988455',
    projectId: 'autilearn-21431',
    storageBucket: 'autilearn-21431.firebasestorage.app',
    iosBundleId: 'com.example.autilearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmMaYNH72bXlR4hlFsh7QKViyp8uIR5wA',
    appId: '1:957482988455:ios:9d63dd16af1f85484cfc82',
    messagingSenderId: '957482988455',
    projectId: 'autilearn-21431',
    storageBucket: 'autilearn-21431.firebasestorage.app',
    iosBundleId: 'com.example.autilearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4m2hv4GN0__-jT-uWCkBPNeCP4yc251g',
    appId: '1:957482988455:web:d1061967504f24cb4cfc82',
    messagingSenderId: '957482988455',
    projectId: 'autilearn-21431',
    authDomain: 'autilearn-21431.firebaseapp.com',
    storageBucket: 'autilearn-21431.firebasestorage.app',
    measurementId: 'G-LK1Q9210GB',
  );
}
