// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgimaW-jCE7gYfU5m6YMnbr9qiLajN6lY',
    appId: '1:705540150945:web:a9a002d5d7d6a0e1b382e0',
    messagingSenderId: '705540150945',
    projectId: 'autilearn-b095b',
    authDomain: 'autilearn-b095b.firebaseapp.com',
    storageBucket: 'autilearn-b095b.firebasestorage.app',
    measurementId: 'G-56L9GM7ZRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUS04Z_ezp9XkRHHDsCJ2Uwf0LxWCe4pg',
    appId: '1:705540150945:android:f01ee2bcfbc37cf7b382e0',
    messagingSenderId: '705540150945',
    projectId: 'autilearn-b095b',
    storageBucket: 'autilearn-b095b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZBJNhD3vZVGjhOoX5jwxei8LYQKulqgM',
    appId: '1:705540150945:ios:1adc2739db28cc79b382e0',
    messagingSenderId: '705540150945',
    projectId: 'autilearn-b095b',
    storageBucket: 'autilearn-b095b.firebasestorage.app',
    iosBundleId: 'com.example.autilearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZBJNhD3vZVGjhOoX5jwxei8LYQKulqgM',
    appId: '1:705540150945:ios:1adc2739db28cc79b382e0',
    messagingSenderId: '705540150945',
    projectId: 'autilearn-b095b',
    storageBucket: 'autilearn-b095b.firebasestorage.app',
    iosBundleId: 'com.example.autilearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgimaW-jCE7gYfU5m6YMnbr9qiLajN6lY',
    appId: '1:705540150945:web:39ef39273e5c73b8b382e0',
    messagingSenderId: '705540150945',
    projectId: 'autilearn-b095b',
    authDomain: 'autilearn-b095b.firebaseapp.com',
    storageBucket: 'autilearn-b095b.firebasestorage.app',
    measurementId: 'G-9CPBWDHG67',
  );

}